# Generated by Django 4.2.7 on 2023-11-16 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "solicitante",
                    models.CharField(max_length=100, verbose_name="Solicitantes"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do chamado")),
                (
                    "iniciado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "ABERTO"),
                            ("EM_ATENDIMENTO", "EM ATENDIMENTO"),
                            ("ENCERRADA", "ENCERRADA"),
                            ("CANCELADA", "CANCELADA"),
                        ],
                        default="OPEN",
                        editable=False,
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fechado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_cliente",
                        to="clientes.cliente",
                        verbose_name="CLIENTE",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_tick",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
