# Generated by Django 4.2.7 on 2023-11-24 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IamgemAtendimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="imagem/atendimentos", verbose_name="Imagem"
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="img_atendimento",
                        to="ticket.atendimento",
                        verbose_name="Atendimento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
