# Generated by Django 4.2.7 on 2023-11-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0002_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="iniciado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "ABERTO"),
                    ("EM_ATENDIMENTO", "EM ATENDIMENTO"),
                    ("ENCERRADA", "ENCERRADA"),
                    ("CANCELADA", "CANCELADA"),
                ],
                default="ABERTO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
