# Generated by Django 4.2.7 on 2023-11-24 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0002_iamgematendimento"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IamgemAtendimento",
            new_name="IamagemAtendimento",
        ),
    ]
