# Generated by Django 4.2.7 on 2023-11-20 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0003_alter_ticket_iniciado_em_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_tick",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
