# Generated by Django 4.2.7 on 2023-11-28 23:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Fabricante",
                "verbose_name_plural": "Frabricantes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedo",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Codigo"
                    ),
                ),
                (
                    "preco_compra",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço de Compra"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_categoria",
                        to="produtos.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fabricante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produto_fabricante",
                        to="produtos.fabricante",
                        verbose_name="Fabricante",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_fornecedor",
                        to="produtos.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
