# Generated by Django 4.2.7 on 2023-12-09 20:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_compra",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
