# Generated by Django 4.2.7 on 2023-11-29 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fornecedor",
            old_name="cnpj",
            new_name="documento",
        ),
    ]
