# Generated by Django 4.2.7 on 2023-11-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_rename_cnpj_fornecedor_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="documento",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Documento"
            ),
        ),
    ]
