# Generated by Django 4.2.7 on 2023-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_alter_fornecedor_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="tipo",
            field=models.CharField(
                choices=[("CPF", "CPF"), ("CNPJ", "CNPJ")],
                default="CNPJ",
                max_length=4,
                verbose_name="Tipo",
            ),
        ),
    ]
