# Generated by Django 4.2.7 on 2023-11-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0004_fornecedor_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="Codigo"
            ),
        ),
    ]
