# Generated by Django 4.2.7 on 2023-12-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0005_alter_produto_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="link_produto",
            field=models.URLField(blank=True, null=True, verbose_name="Link Produto"),
        ),
    ]
