# Generated by Django 4.2.7 on 2024-06-02 16:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solicitante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Solicitante')),
                ('status', models.IntegerField(choices=[(0, 'Não Execultado'), (1, 'Em Execução'), (2, 'Finalizado'), (3, 'Aguardando Equipamento(s)')], default=0, verbose_name='Situação')),
                ('emissao', models.DateTimeField(verbose_name='Emissao')),
                ('inicio_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('descricao', models.TextField(verbose_name='Descrição da OS')),
                ('resolucao', models.TextField(blank=True, null=True, verbose_name='Resolução')),
                ('fim_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('tempo_total', models.CharField(blank=True, editable=False, null=True, verbose_name='Tempo Total')),
                ('tempo_servico', models.CharField(blank=True, editable=False, null=True, verbose_name='Tempo Servico')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('total_equipamentos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Equipamentos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_cliente', to='clientes.cliente', verbose_name='Cliente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('porcentagem', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentagem')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Compra')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_OS', to='ordemdeservicos.ordemdeservico', verbose_name='OS')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_produto', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
