# Generated by Django 4.2.7 on 2024-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemdeservicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='emissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emissao'),
        ),
    ]
