# Generated by Django 4.2.7 on 2024-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemdeservicos', '0002_alter_ordemdeservico_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('BAIXA', 'BAIXA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA'), ('URGENTE', 'URGENTE')], default='BAIXA', max_length=15, null=True, verbose_name='Prioridade'),
        ),
    ]
