# Generated by Django 4.2.7 on 2024-06-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemdeservicos', '0006_alter_ordemdeservico_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemos',
            name='porcentagem',
        ),
        migrations.RemoveField(
            model_name='itemos',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemos',
            name='item',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item'),
        ),
    ]
