# Generated by Django 4.2.7 on 2024-08-03 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0006_alter_orcamento_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('forma_pagamento', models.CharField(choices=[('AVISTA', 'AVISTA'), ('CARTAO', 'CARTÃO'), ('BOLETO', 'BOLETO'), ('CONVENIO', 'CONVENIO')], max_length=15, verbose_name='Forma de Pagamento')),
                ('acrecimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Acrécimo')),
                ('entrada', models.BooleanField(default=False)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Entrada')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bruto')),
                ('qt_parcelas', models.IntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('valor_acrecimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Acrecimo')),
                ('total_acrecimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Acrécimo')),
                ('orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orcamentos.orcamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
