# Generated by Django 4.2.7 on 2024-08-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_alter_orcamento_validade'),
        ('payment', '0006_alter_payment_acrecimo_alter_payment_valor_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orcamentos.orcamento', verbose_name='Orcamento'),
        ),
    ]
