# Generated by Django 4.2.7 on 2024-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_desconto_payment_total_desconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_desconto',
        ),
    ]
