# Generated by Django 4.2.7 on 2024-08-04 22:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_payment_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Desconto'),
        ),
    ]
