# Generated by Django 4.2.7 on 2024-08-04 23:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_payment_total_acrecimo_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='valor_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto'),
        ),
    ]
