# Generated by Django 4.2.7 on 2023-12-04 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validade",
                    models.DateField(
                        default=datetime.date(2023, 12, 19), verbose_name="Validade"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Não Enviado"),
                            (1, "Em Analise"),
                            (2, "Aprovado"),
                            (3, "Cancelada"),
                        ],
                        default=0,
                        verbose_name="Situação",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "total_equipamentos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Equipamentos",
                    ),
                ),
                (
                    "total_mao_de_obra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Mão de Obra",
                    ),
                ),
                (
                    "total_lucro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Lucro",
                    ),
                ),
                (
                    "total_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Compra",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamento_cliente",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemProduto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "porcentagem",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Porcentagem",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preço",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produto_orcamento",
                        to="orcamentos.orcamento",
                        verbose_name="Orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_produto",
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Produto",
                "verbose_name_plural": "itens Produtos",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="InformacoesOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("titulo", models.CharField(verbose_name="Descrição")),
                (
                    "descricao",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                (
                    "orcamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orcamentos.orcamento",
                        verbose_name="Descricao",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
