# Generated by Django 4.2.7 on 2024-06-02 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2024, 6, 17), verbose_name='Validade'),
        ),
    ]
