# Generated by Django 4.2.7 on 2023-12-05 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orcamentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orcamento",
            name="descricao",
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Não Enviado"),
                    (1, "Em Analise"),
                    (2, "Aprovado"),
                    (3, "Cancelada"),
                    (4, "Regeitado"),
                ],
                default=0,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2023, 12, 20), verbose_name="Validade"
            ),
        ),
    ]
