# Generated by Django 4.2.7 on 2023-12-19 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orcamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2024, 1, 3), verbose_name="Validade"
            ),
        ),
    ]
