# Generated by Django 4.2.7 on 2023-12-29 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orcamentos", "0002_orcamento_descricao_alter_orcamento_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2024, 1, 15), verbose_name="Validade"
            ),
        ),
    ]
