# Generated by Django 4.2.7 on 2023-12-06 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0001_initial"),
        (
            "orcamentos",
            "0002_remove_orcamento_descricao_alter_orcamento_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2023, 12, 21), verbose_name="Validade"
            ),
        ),
        migrations.CreateModel(
            name="ItemMaoDeObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mao_obra_orcamento",
                        to="orcamentos.orcamento",
                        verbose_name="Orçamento",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_servico",
                        to="servicos.servico",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Serviço",
                "verbose_name_plural": "Itens Serviços",
                "ordering": ["-created"],
            },
        ),
    ]
