# Generated by Django 4.2.7 on 2023-12-09 20:21

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orcamentos", "0003_alter_orcamento_validade_itemmaodeobra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmaodeobra",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="itemmaodeobra",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="itemproduto",
            name="preco",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço de Compra",
            ),
        ),
        migrations.AlterField(
            model_name="itemproduto",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2023, 12, 25), verbose_name="Validade"
            ),
        ),
    ]
