# Generated by Django 4.2.7 on 2023-12-10 11:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orcamentos",
            "0004_alter_itemmaodeobra_total_alter_itemmaodeobra_valor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemproduto",
            name="porcentagem",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=16,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Porcentagem",
            ),
        ),
    ]
